version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:15.3
    ports:
      - 5432:5432
    volumes:
      - ./sql/postgres.sql:/main.sql
      - ./sql/random-data.sql:/data.sql
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust