version: '3.9'

networks:
  ddosnetwork:
    ipam:
      driver: default
      config:
        - subnet: 172.15.0.0/16
          gateway: 172.15.0.1

services:
  ddos:
    build:
      context: ./hping3
    command: tail -f /dev/null
    networks:
      - ddosnetwork

  protected:
    container_name: protected_nginx
    image: nginx:1.25-alpine
    ports:
      - 8001:80
    volumes:
      - ./servers/protected.conf:/etc/nginx/conf.d/default.conf
      - ./servers/image.jpeg:/var/www/image.jpeg
    networks:
      ddosnetwork:
        ipv4_address: 172.15.0.4

  unprotected:
    container_name: unprotected_nginx
    image: nginx:1.25-alpine
    ports:
      - 8002:80
    volumes:
      - ./servers/unprotected.conf:/etc/nginx/conf.d/default.conf
      - ./servers/image.jpeg:/var/www/image.jpeg
    networks:
      ddosnetwork:
        ipv4_address: 172.15.0.5

  # monitor
  grafana:
    hostname: grafana
    container_name: grafana
    image: grafana/grafana:8.0.2
    env_file: ./grafana/configuration.env
    expose:
      - 3000
    ports:
      - 3000:3000
    depends_on:
      - influxdb
    links:
      - influxdb
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    networks:
      - ddosnetwork

  telegraf:
    hostname: telegraf
    container_name: telegraf
    image: telegraf:1.18-alpine
    platform: linux/amd64
    user: root
    entrypoint: /bin/bash -c "chmod 666 /var/run/docker.sock && /entrypoint.sh telegraf"
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/rootfs/proc:ro
    links:
      - influxdb
    networks:
      - ddosnetwork

  influxdb:
    hostname: influxdb
    container_name: influxdb
    image: influxdb:1.8-alpine
    platform: linux/amd64
    env_file: ./influxdb/configuration.env
    volumes:
      - ./:/imports
    networks:
      - ddosnetwork