version: '3.9'

networks:
  dnsnetwork:
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1

services:
  client:
    image: nginx:1.25-alpine
    restart: always
    volumes:
        - ./client/nginx.conf:/etc/nginx/conf.d/default.conf
    dns:
      - 172.16.238.10
    depends_on:
      - bind
    ports:
      - 3000:80
    networks:
      - dnsnetwork

  bind:
    build:
      context: ./bind
    restart: always
    volumes:
        - ./data/bind:/var/cache/bind
    environment:
      - WEBMIN_ENABLED=false
    ports:
      - 53:53/udp
      - 53:53/tcp
      - 10000:10000/tcp
    networks:
      dnsnetwork:
        ipv4_address: 172.16.238.10

  lb1:
    image: nginx:1.25-alpine
    volumes:
      - ./lb/rest.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8001:80
    depends_on:
      - node1
    networks:
      dnsnetwork:
        ipv4_address: 172.16.238.200

  lb2:
    image: nginx:1.25-alpine
    volumes:
      - ./lb/us.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8002:80
    depends_on:
      - node2
      - node3
    networks:
      dnsnetwork:
        ipv4_address: 172.16.238.100

  node1:
    image: nginx:1.25-alpine
    volumes:
      - ./nodes/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nodes/assets/image1.jpeg:/var/www/image.jpeg
    networks:
      - dnsnetwork

  node2:
    image: nginx:1.25-alpine
    volumes:
      - ./nodes/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nodes/assets/image2.jpeg:/var/www/image.jpeg
      - ./nodes/assets:/var/www/
    networks:
      - dnsnetwork

  node3:
    image: nginx:1.25-alpine
    volumes:
      - ./nodes/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nodes/assets/image3.jpeg:/var/www/image.jpeg
    networks:
      - dnsnetwork