-- levels
SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;

SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;

SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

SET SESSION TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SHOW VARIABLES LIKE 'transaction_isolation';


-- trx 1

BEGIN;

SELECT * FROM users WHERE id = 1;


UPDATE users SET status = 'trx1' WHERE id = 1;

ROLLBACK;
COMMIT;

-- trx 2

BEGIN;

SELECT * FROM users WHERE id = 1;

UPDATE users SET status = 'trx2' WHERE id = 1;

ROLLBACK;
COMMIT;