BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ;

BEGIN TRANSACTION ISOLATION LEVEL READ COMMITTED;

BEGIN TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SHOW transaction_isolation;

-- trx 1

SELECT * FROM users WHERE id = 1;

UPDATE users SET status = 'trx1' WHERE id = 1;

ROLLBACK;

COMMIT;

-- trx 2

SELECT * FROM users WHERE id = 1;

UPDATE users SET status = 'trx2' WHERE id = 1;

ROLLBACK;

COMMIT;