-- Active: 1690543510694@@127.0.0.1@5432@postgres

BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ;

BEGIN TRANSACTION ISOLATION LEVEL READ COMMITTED;

BEGIN TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SHOW transaction_isolation;

-- trx 1

SELECT * FROM users WHERE id = 1;

SELECT * FROM users WHERE id = 1;

ROLLBACK;

-- trx 2

UPDATE users SET status = 'active' WHERE id = 1;

ROLLBACK;