version: '3.9'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306

  postgres:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
